<a href="https://colab.research.google.com/github/prithanimavat/PrithaNimavat_MachineLearning_92400588037/blob/main/ColumnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [29]:
print(df.cough.value_counts())
print()
print()

print(df.city.value_counts())
print()
print()

print(df.has_covid.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64


city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64


has_covid
No     55
Yes    45
Name: count, dtype: int64

In [30]:
'''

age-numeric column
gender-nominal categorical column(one-hot encoding)
cough-nominal categorical column(ordinal encoding)
city-nominal categorical column
has_covid-nominal categorical column
fever-numeric column. has missing values. will apply simple imputer

'''

'\n\nage-numeric column\ngender-nominal categorical column(one-hot encoding)\ncough-nominal categorical column(ordinal encoding)\ncity-nominal categorical column\nhas_covid-nominal categorical column\nfever-numeric column. has missing values. will apply simple imputer\n\n'

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
x=df.iloc[:,0:5]
y=df.drop(x,axis='columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [14]:
#Train-Test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age  gender  fever   cough       city
68   54  Female  104.0  Strong    Kolkata
52   47  Female  100.0  Strong  Bangalore
62   56  Female  104.0  Strong  Bangalore
4    65  Female  101.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata


   has_covid
68        No
52       Yes
62       Yes
4         No
92        No

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

si= SimpleImputer()
le=LabelEncoder()

y_train.has_covid=le.fit_transform(y_train.has_covid)
y_test.has_covid=le.transform(y_test.has_covid)

x_train['fever']=si.fit_transform(x_train[['fever']])
x_test['fever']=si.transform(x_test[['fever']])

print()

In [20]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()

x_train[['cough']]=oe.fit_transform(x_train[['cough']])
x_test[['cough']]=oe.transform(x_test[['cough']])

print()

In [15]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse_output=False)

x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [31]:
transformer=[('trans1',SimpleImputer(),['fever']),
             ('trans2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
             ('trans3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
             ]

ct=ColumnTransformer(
    transformers=transformer,
    remainder='passthrough').set_output(transform='pandas')

x_train_trans=ct.fit_transform(x_train)

x_train_trans.sample(5)

NameError: name 'ColumnTransformer' is not defined